# -*- coding: utf-8 -*-
"""decision tree classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ItN8d5aTREb6i3o-8GxYsMkrNENzHhj
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder

iris = pd.read_csv("/home/iris.csv")

iris

#Bar plot for categorical column "variety"
import seaborn as sns
counts = iris["variety"].value_counts()
sns.barplot(data = counts)

iris.info()

iris[iris.duplicated(keep = False)]

"""# observations
* There are 150 rows and 5 columns
* There are no Null values
* There is one duplicated row
* The x-columns are sepal.length, sepal.width, petal.length and petal.widtl
* All the x-columns are continuous
* The y-column is "variety" which is categorical
* There are three flower categories (classes)
"""

#drop the duplicates
iris = iris.drop_duplicates(keep='first')

# Ensure further that no duplicated rows are present
iris[iris.duplicated]

# Reset the index
iris = iris.reset_index(drop=True)
iris

