# -*- coding: utf-8 -*-
"""descriptive stats

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11hfCe2axcky-ja0RgFZ2sNCushfgLIUm
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/home/universities.csv")
df

#mean value of SAT score
np.mean(df["SAT"])

#median value of SAT score
np.median(df["SAT"])

#standard deviation of data
np.std(df["GradRate"])

#find the variance
np.var(df["SFRatio"])

df.describe()

#visualize the GradRate using histogram
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(6,3))
plt.title("Acceptance Ratio")
plt.hist(df["Accept"])

sns.histplot(df["Accept"])

sns.histplot(df["Accept"], kde = True)

#create a pandas series of batsman1 scores
s1 = [10,20,30,50,40,45,34,12]
scores1 = pd.Series(s1)
scores1

plt.boxplot(scores1, vert=False)

#create a pandas series of batsman scores
s2 = [10,20,30,50,40,150,130,190]
scores2 = pd.Series(s2)
scores2

plt.boxplot(scores2, vert=False)

df = pd.read_csv("/home/universities.csv")
print(df)
#print box plot for SAT column
plt.boxplot(df["SAT"])