# -*- coding: utf-8 -*-
"""descriptive stats

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11hfCe2axcky-ja0RgFZ2sNCushfgLIUm
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/home/universities.csv")
df

#mean value of SAT score
np.mean(df["SAT"])

#median value of SAT score
np.median(df["SAT"])

#standard deviation of data
np.std(df["GradRate"])

#find the variance
np.var(df["SFRatio"])

df.describe()

#visualize the GradRate using histogram
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(6,3))
plt.title("Acceptance Ratio")
plt.hist(df["Accept"])

sns.histplot(df["Accept"])



sns.histplot(df["Accept"], kde = True)

