# -*- coding: utf-8 -*-
"""eda1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MoUfC7cOJozPhn7z40xR6zFjFMkOkKiZ
"""

#load the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('/home/data_clean.csv')
data

data.info()



#data structure
print(type(data))
print(data.shape)

data.shape

#data types
data.dtypes

#drop  duplicate column and unnamed column
data1 = data.drop(['Unnamed: 0',"Temp C"], axis=1)
data1

#Convert the month column data type to integer data type
data1['Month']=pd.to_numeric(data['Month'],errors='coerce')
data1.info()

#checking for duplicated row in the table
#print the duplicated row
data1[data1.duplicated(keep = False)]

#change column names (reanme the columns)
data1.rename({'Solar.R':'Solar'},axis=1,inplace=True)
data1

#display data info
data1.info()

#display data1 missing values count in each column using isnull().sum()
data1.isnull().sum()

#visualize data1 missing values
cols = data1.columns
colours = ['black', 'yellow']
sns.heatmap(data1[cols].isnull(),cmap=sns.color_palette(colours),cbar = True)

#find the mean and median values of each numeric column
median_ozone = data1['Ozone'].median()
median_solar = data1['Solar'].median()
median_wind = data1['Wind'].median()
mean_ozone = data1['Ozone'].mean()
mean_solar = data1['Solar'].mean()
mean_wind = data1['Wind'].mean()
print("Median of ozone: ",median_ozone)
print("Median of solar: ",median_solar)
print("Median of wind: ",median_wind)
print("Mean of ozone: ",mean_ozone)
print("Mean of solar: ",mean_solar)
print("Mean of wind: ",mean_wind)

#replace the ozone missimg values with median
data1['Ozone'] = data1['Ozone'].fillna(median_ozone)
data1.isnull().sum()

#replace the solar missing values with median
data1['Solar'] = data1['Solar'].fillna(median_solar)
data1.isnull().sum()
data1['Wind'] = data1['Wind'].fillna(median_wind)
data1.isnull().sum()