# -*- coding: utf-8 -*-
"""eda1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MoUfC7cOJozPhn7z40xR6zFjFMkOkKiZ
"""

#load the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('/home/data_clean.csv')
data

data.info()

#data structure
print(type(data))
print(data.shape)

data.shape

#data types
data.dtypes

#drop  duplicate column and unnamed column
data1 = data.drop(['Unnamed: 0',"Temp C"], axis=1)
data1

#Convert the month column data type to integer data type
data1['Month']=pd.to_numeric(data['Month'],errors='coerce')
data1.info()

#checking for duplicated row in the table
#print the duplicated row
data1[data1.duplicated(keep = False)]