# -*- coding: utf-8 -*-
"""K-MEANS (10/1/2025)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I5N3L5H-MYAUWOOe3_TXPyROX3gHgwHk
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
from sklearn.cluster import KMeans

"""# Clustering-Divide the universities in to group"""

univ = pd.read_csv("/home/Universities (1).csv")
univ

univ.info()

univ.describe()

univ.isnull().sum()

"""# standardisation function"""

#Read all numeric columns in to univ1
univ1 = univ.iloc[:,1:]

univ1

cols = univ1.columns

# Standardisation function
from sklearn. preprocessing import StandardScaler
scaler = StandardScaler()
scaled_univ_df = pd. DataFrame(scaler.fit_transform(univ1), columns = cols )
scaled_univ_df

