# -*- coding: utf-8 -*-
"""Linear regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11vvh5n9vrTxnepZNnhERZQeUnceDaN9W
"""

#Load the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data1 = pd.read_csv("/home/NewspaperData.csv")
print(data1)

data1

data1.info()

data1.isnull().sum()

data1.describe()

# Boxplot for daily column
plt.figure(figsize=(6,3))
plt. title("Box plot for Daily Sales")
plt.boxplot(data1["daily"], vert = False)
plt. show()

sns.histplot(data1['daily'], kde = True,stat='density',)
plt.show()

sns.histplot(data1['sunday'], kde = True,stat='density',)
plt.show()

"""Observations

* There are no missing values
* The daily column values appears to be right-skewed
* The sunday column vaues also appear to be right-skewed
* There are two outliers in both daily column and also in sunday column as observed from the boxplots

# Scatter plot and Correlation strength
"""

x= data1["daily"]
y = data1["sunday"]
plt.scatter(data1["daily"], data1["sunday"])
plt.xlim(0, max(x) + 100)
plt.ylim(0, max(y) + 100)
plt.show()

data1["daily"].corr(data1["sunday"])

data1[["daily", "sunday"]].corr()

"""observation

*  The relationship between x (daily) and y (sunday) is seen to be linear as seen from scatter plot
* The correlation is strong postive with Pearson's correlation coefficient of 0.958154

# Fit a linear regression model
"""

# Build regression model

import statsmodels.formula.api as smf
model1 = smf.ols("sunday~daily",data = data1).fit()

model1.summary()