# -*- coding: utf-8 -*-
"""numpy array practice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZPNc9Z7eS8fKvmJiwvpqpiLlVzArMCFT
"""

import numpy as np

#dir(np)

x = np.array([40,67,57,5])
print(x)
print(type(x))

x = np.array(["G",67,57,5.9])
print(x)
print(type(x))
print(x.dtype)

#create a 2d array
a2 = np.array([[20,40],[30,60]])
print(a2)
print(type(a2))
print(a2.shape)

#create a 1d array
a = np.array([20,40,30,60])
print(a)
print(type(a))

a = np.array([20,40,30,60])
b = a.reshape(2,2)
print(b)
print(b.shape)

#create an array with arrange()
c = np.arange(3,20)
print(c)
type(c)

d = np.array([1.345,3.567,2.789])
print(d)
print(d.dtype)

#use of np.sqrt()
print(np.sqrt(d))

#2d array

#use as type() to convert the data
a1 = np.array([[2,5,6,7],[3,4,8, np.NAN]])
print(a1)
a1.dtype

a1_copy = a1.astype(float)
print(a1_copy)
a1_copy.dtype

#mathematical on rows and columns
a2 =np.array([[2,7,4],[41,5,6],[10,12,1]])
a2

print(a2.sum(axis = 1))
print(a2.sum(axis=0))

#find the mean values along row and column
print(np.mean(a2, axis=1))
print(np.mean(a2, axis=0))

#matrix operation
a3 =np.array([[2,7,4],[41,5,6],[10,12,1]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)

a3 =np.array([[2,7,4],[41,5,6],[10,12,1]])
print(a3)
np.fill_diagonal(a3,1)
print(a3)

#define two matrices and  multiply them
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

#perform matrix multiplication
C = np.matmul(A,B)
print(C)

#print transpose of matrix
print(A.T)
print(B.T)

#acessing the array elements
a4 = np.array([[3,4,5],[7,2,8],[9,1,6],[10,9,18]])
a4

a4[2][1]

#slicing of array
a4[:,1:]

a4[1:3,0:2]