# -*- coding: utf-8 -*-
"""statparams

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yy5_Nu0c4RFXiMHq-aL4eGmx0AyfcWuh
"""

def mean_value(L):
  avg=sum(L)/len(L)
  return avg

mean_value=([10,20,37,40,67,89])

def mode_value(s):
  mode = max(set(s),key=s.count)
  return mode

mode_value([1,3,4,5,6,4,2])

def mode_value(L):
  mode = max(set(L),key=L.count)
  return mode

mode_value(["G","G","L","G","L","G"])

def mode_value(L):
  s = set(L)
  d={}
  for x in s:
    d[x]=L.count(x)
  return d

mode_value(["G","G","L","G","L","G"])

def mode_value(L):
  s = set(L)
  d={}

  for x in s:
    d[x]=L.count(x)

    m = max(d.values())

    for k in d.keys():
      if d[k] == m:
        return k

L =["G","G","L","G","L","G"]
mode_value(L)

def mode_value(L):
  s = set(L)
  d={}

  for x in s:
    d[x]=L.count(x)

    m = max(d.values())

    for k in d.keys():
      if d[k] == m:
        return k

L =[1,2,3,5,3,4]
mode_value(L)